### ISSUE TITLE
Add light/dark designs for compact menu

### ISSUE THREAD

**Issue by lal65** [PSU-OOE/components#249]
Add new comapct menu color properties:

```css
:root {
  --compact-menu-bars-color--light: var(--pugh-blue);
  --compact-menu-text-color--light: var(--white);
  --compact-menu-bars-hover-color--light: var(--white);
  --compact-menu-text-hover-color--light: var(--white);
  --compact-menu-bars-active-color--light: var(--keystone-light);

  --compact-menu-bars-color--dark: var(--beaver-blue);
  --compact-menu-text-color--dark: var(--beaver-blue);
  --compact-menu-bars-hover-color--dark: var(--nittany-navy);
  --compact-menu-text-hover-color--dark: var(--nittany-navy);
  --compact-menu-bars-active-color--dark: var(--pa-link);
}
```

Make these properties auto-contrast on light/dark

```
:root, [data-light] {
  --compact-menu-bars-color: var(--compact-menu-bars-color--dark);
  --compact-menu-text-color: var(--compact-menu-text-color--dark);
  --compact-menu-bars-hover-color: var(--compact-menu-bars-hover-color--dark);
  --compact-menu-text-hover-color: var(--compact-menu-text-hover-color--dark);
  --compact-menu-bars-active-color: var(--compact-menu-bars-active-color--dark);
}

[data-dark] {
  --compact-menu-bars-color: var(--compact-menu-bars-color--light);
  --compact-menu-text-color: var(--compact-menu-text-color--light);
  --compact-menu-bars-hover-color: var(--compact-menu-bars-hover-color--light);
  --compact-menu-text-hover-color: var(--compact-menu-text-hover-color--light);
  --compact-menu-bars-active-color: var(--compact-menu-bars-active-color--light);
}
```

Finally, apply these properties to the component; removing the hard-coded colors.
